name: Deploy Code

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: "fn-azfuncs-digibanks99" # set this to your function app name on Azure
  FUNCTION_APP_PACKAGE_PATH: "." # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: "6.0.x" # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore AzFunc.sln

      - name: Test
        run: dotnet test --no-build --verbosity normal AzFunc.sln

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore AzFunc.sln

      - name: Build
        run: dotnet build --no-restore AzFunc.sln

      - name: Publish
        run: |
          pushd './${{ env.FUNCTION_APP_PACKAGE_PATH }}'
          dotnet publish src/AzFuncs/AzFuncs.csproj --configuration Release --output ./output
          popd

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: "${{ env.FUNCTION_APP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
